name: feedflow
description: A modern RSS/Atom/JSON Feed reader with vertical scrolling cards
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # HTTP & Feed Parsing
  http: ^1.1.0
  xml: ^6.3.0
  
  # WebView
  webview_flutter: ^4.4.2
  
  # URL Launcher
  url_launcher: ^6.2.1
  
  # Image Caching
  cached_network_image: ^3.3.0
  
  # Date Formatting
  intl: ^0.18.1
  
  # Fonts with multilingual support
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/feeds.json